from . import MeanTeacherv1
from . import MeanTeacherv2
from . import PIv1
from . import PIv2
from . import VATv1
from . import VATv2
from . import ICTv1
from . import ICTv2
from . import ePseudoLabel2013v1
from . import ePseudoLabel2013v2
from . import iPseudoLabel2013v1
from . import iPseudoLabel2013v2
from . import eTempensv1
from . import eTempensv2
from . import iTempensv1
from . import iTempensv2
from . import MixMatch
from . import eMixPseudoLabelv1
from . import eMixPseudoLabelv2
